#ifndef READOUT_H
#define READOUT_H
#include <stdint.h>

/* Auto-generated by phase2/tests/gen_on_target_readout.py — do not hand-edit numbers.
 *
 * "Readout" = the small trained classifier on top of the fixed reservoir.
 * MCU inference path:
 *   TRACE (Q15) → reservoir_run → R
 *   → 12 features (mean, std, last × 4 neurons)
 *   → z[i] = (feat[i] - READOUT_MEAN[i]) / READOUT_SCALE[i]   // StandardScaler
 *   → logits[c] = READOUT_INTERCEPT[c] + sum_i READOUT_COEF[c][i] * z[i]
 *   → class = argmax(logits)
 *
 * Trained on Q15 LUT reservoir features (same as phase2/rc/reservoir_q15.c),
 * StandardScaler + LogisticRegression on all data/raw traces.
 */
#define READOUT_N_FEATURES 12 /* 3 stats × 4 neurons */
#define READOUT_N_CLASSES 4

/* StandardScaler: per-feature training-set mean */
static const float READOUT_MEAN[READOUT_N_FEATURES] = {
  /* means[0..3], stds[0..3], lasts[0..3] — same order as feat[] */
  1.12111345e-01f, 3.47440038e-02f, 3.76451819e-02f, 1.49707823e-01f,
  4.57230965e-01f, 3.19051788e-01f, 3.08749036e-01f, 4.21159523e-01f,
  -8.16082248e-01f, -2.00316194e-01f, -3.37040889e-01f, -8.65076437e-01f
};

/* StandardScaler: per-feature training-set std (sklearn scale_) */
static const float READOUT_SCALE[READOUT_N_FEATURES] = {
  1.31035296e-01f, 9.57890247e-02f, 4.49259964e-02f, 1.23309835e-01f,
  2.10857020e-01f, 1.87525747e-01f, 1.40231895e-01f, 2.18573222e-01f,
  1.70872121e-01f, 5.21252939e-01f, 3.98297998e-01f, 5.49274075e-02f
};

/* LogisticRegression coef_[class][feature] */
static const float READOUT_COEF[READOUT_N_CLASSES][READOUT_N_FEATURES] = {
  /* class 0 benign */
  { -8.39344877e-01f, -1.62098333e+00f, -2.37531718e-01f, -1.24644608e-01f, -5.31766228e-01f, 1.53585820e+00f, -5.26674079e-02f, -8.79646763e-02f, 2.29987129e-01f, -6.25880183e-02f, -1.07177574e-01f, -4.72533245e-02f },
  /* class 1 branch_abuse */
  { -1.52289616e-02f, -3.58350270e-02f, 1.12966571e-01f, -3.63983390e-01f, -5.22899362e-01f, -1.69012192e+00f, 1.60658683e-02f, -2.82977782e-01f, -1.14322644e-01f, 9.12419542e-01f, -7.09839620e-01f, 2.72423743e-01f },
  /* class 2 cache_thrash */
  { 1.26486076e-01f, 9.54075873e-01f, 6.78224156e-04f, 1.79763863e-01f, 1.30545329e-01f, -1.55323066e-01f, -7.09366796e-01f, -7.31517591e-01f, -1.05713803e-01f, -4.14047977e-01f, 6.17422887e-01f, 2.33651596e-01f },
  /* class 3 row_hammer */
  { 7.28087763e-01f, 7.02742483e-01f, 1.23886923e-01f, 3.08864134e-01f, 9.24120261e-01f, 3.09586790e-01f, 7.45968336e-01f, 1.10246005e+00f, -9.95068145e-03f, -4.35783547e-01f, 1.99594307e-01f, -4.58822014e-01f }
};

static const float READOUT_INTERCEPT[READOUT_N_CLASSES] = {
  2.23620741e+00f, -5.10156804e-01f, 8.14418965e-01f, -2.54046957e+00f
};

static const char *READOUT_CLASS_NAMES[READOUT_N_CLASSES] = {
  "benign",
  "branch_abuse",
  "cache_thrash",
  "row_hammer"
};

/* Expected argmax for phase2/rc/trace_benign.h and trace_attack.h */
#define GOLDEN_CLASS_BENIGN 0 /* benign */
#define GOLDEN_CLASS_ATTACK 1 /* branch_abuse */
#endif
