"""export StandardScaler + LogisticRegression for on-target MCU.

Uses the same Q15 LUT reservoir path as the C firmware (not float np.tanh),
so feature distributions match what the board will compute.

Run from repo root:
  /opt/anaconda3/bin/python phase2/tests/gen_on_target_readout.py
"""
import os
import sys
import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
sys.path.insert(0, ROOT)

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

from rc.data import load_all_traces, load_trace
from rc.features import trace_features
from rc.reservoir import Reservoir

SCALE = 32768
N_TAB, LO, HI = 256, -3.0, 3.0
RES_N, RES_D = 4, 4
TRACE_LEN = 100
BENIGN_CSV = os.path.join(ROOT, "data/raw/benign/matmul_1.csv")
ATTACK_CSV = os.path.join(ROOT, "data/raw/branch_abuse/branch_abuse_1.csv")
OUT = os.path.join(ROOT, "phase2/rc/readout.h")


def to_q15(x):
    return np.clip(np.round(np.asarray(x, dtype=np.float64) * SCALE), -32768, 32767).astype(np.int16)


def build_tanh_table():
    return to_q15(np.tanh(np.linspace(LO, HI, N_TAB)))


def tanh_q15(x, table):
    x = np.float32(x)
    x = np.clip(x, np.float32(LO), np.float32(HI))
    pos = (x - np.float32(LO)) / np.float32(HI - LO) * np.float32(N_TAB - 1)
    i = np.floor(pos).astype(np.int32)
    i = np.minimum(i, N_TAB - 2)
    frac = pos - np.float32(i)
    a = table[i].astype(np.float32) / np.float32(SCALE)
    b = table[i + 1].astype(np.float32) / np.float32(SCALE)
    y = (np.float32(1) - frac) * a + frac * b
    return to_q15(np.float64(y))


def make_weights():
    res = Reservoir(4, 4, 0.6, 0.4, 0.7, seed=0)
    return (
        res.W.astype(np.int16),
        res.Wr.astype(np.int16),
        int(to_q15(0.6)),
        int(to_q15(0.4)),
    )


def step(x_q15, r, W, Wr, GI, GF, table):
    r_out = np.zeros(RES_N, dtype=np.int16)
    for i in range(RES_N):
        s = np.int64(0)
        for j in range(RES_D):
            s += np.int64(W[i, j]) * np.int64(x_q15[j])
        new_c = (s * np.int64(GI)) >> 15
        old_c = ((np.int64(Wr[i, i]) * np.int64(r[i])) * np.int64(GF)) >> 15
        pre = new_c + old_c
        r_out[i] = tanh_q15(np.float32(pre) / np.float32(SCALE), table)
    return r_out


def run_q15(X_float, W, Wr, GI, GF, table):
    X = np.clip(X_float, -1.0, 1.0)
    Xq = to_q15(X)
    T = Xq.shape[0]
    R = np.zeros((T, RES_N), dtype=np.float64)
    r = np.zeros(RES_N, dtype=np.int16)
    for t in range(T):
        r = step(Xq[t], r, W, Wr, GI, GF, table)
        R[t] = r.astype(np.float64) / SCALE
    return R


def bake_csv(csv_path, n=TRACE_LEN):
    X = load_trace(csv_path)
    if X is None or len(X) < n:
        raise SystemExit(f"bad trace {csv_path}")
    return X[:n]


def fmt_arr(a):
    return ", ".join(f"{float(v):.8e}f" for v in np.asarray(a).reshape(-1))


def main():
    W, Wr, GI, GF = make_weights()
    table = build_tanh_table()

    traces, labels, classes = load_all_traces(os.path.join(ROOT, "data/raw"))
    print(f"Training on {len(traces)} traces, classes={classes}")

    feats = []
    for tr in traces:
        R = run_q15(tr, W, Wr, GI, GF, table)
        feats.append(trace_features(R))
    X = np.stack(feats)
    y = labels

    clf = Pipeline([
        ("scaler", StandardScaler()),
        ("lr", LogisticRegression(max_iter=2000)),
    ])
    clf.fit(X, y)
    acc = clf.score(X, y)
    print(f"train accuracy (LUT reservoir features): {acc:.4f}")

    scaler = clf.named_steps["scaler"]
    lr = clf.named_steps["lr"]

    # Golden labels for the two baked MCU traces
    Rb = run_q15(bake_csv(BENIGN_CSV), W, Wr, GI, GF, table)
    Ra = run_q15(bake_csv(ATTACK_CSV), W, Wr, GI, GF, table)
    pred_b = int(clf.predict(trace_features(Rb).reshape(1, -1))[0])
    pred_a = int(clf.predict(trace_features(Ra).reshape(1, -1))[0])
    print(f"golden TRACE_BENIGN  -> class {pred_b} ({classes[pred_b]})")
    print(f"golden TRACE_ATTACK  -> class {pred_a} ({classes[pred_a]})")

    n_feat = X.shape[1]
    n_cls = len(classes)
    coef_rows = []
    for c in range(n_cls):
        coef_rows.append("  { " + fmt_arr(lr.coef_[c]) + " }")
    coef_block = ",\n".join(coef_rows)

    names = ",\n  ".join(f'"{c}"' for c in classes)
    text = f"""#ifndef READOUT_H
#define READOUT_H
#include <stdint.h>

/* Auto-generated by phase2/tests/gen_on_target_readout.py
 * Features from Q15 LUT reservoir (matches phase2/rc/reservoir_q15.c).
 * Pipeline: StandardScaler + LogisticRegression, fit on all data/raw traces.
 */
#define READOUT_N_FEATURES {n_feat}
#define READOUT_N_CLASSES {n_cls}

static const float READOUT_MEAN[READOUT_N_FEATURES] = {{ {fmt_arr(scaler.mean_)} }};
static const float READOUT_SCALE[READOUT_N_FEATURES] = {{ {fmt_arr(scaler.scale_)} }};
static const float READOUT_COEF[READOUT_N_CLASSES][READOUT_N_FEATURES] = {{
{coef_block}
}};
static const float READOUT_INTERCEPT[READOUT_N_CLASSES] = {{ {fmt_arr(lr.intercept_)} }};
static const char *READOUT_CLASS_NAMES[READOUT_N_CLASSES] = {{
  {names}
}};

/* Expected argmax on baked MCU traces (host check) */
#define GOLDEN_CLASS_BENIGN {pred_b}
#define GOLDEN_CLASS_ATTACK {pred_a}
#endif
"""
    open(OUT, "w").write(text)
    print(f"wrote {OUT}")
    print("Stage 2 done.")


if __name__ == "__main__":
    main()
